config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :donations
  resources "contacts", only: [:new, :create]
  resources :comments
  resources :submissions do
    member do
      put "vote", to: "submissions#upvote"
    end
  end
 

  root 'submissions#featured'
  get 'featured' => 'submissions#featured'
  get 'featured' => 'featured#index'
  get 'donations' => 'donations#new'
  get 'contacts' => 'contacts#new'
  get 'about' => 'donations#about'

  get 'users' => 'users#show', as: :user

end

app/models/submission.rb
class Submission < ActiveRecord::Base
	has_many :comments
	belongs_to :user

	acts_as_votable


	
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  authorize_resource

  before_action :set_submission, only: [:show, :edit, :update, :destroy]

def donations
  
end
  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  def your_submission
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @comment = Comment.new
   
    @submission = Submission.find(params[:id])
  @submission.save

  @submission.liked_by @user

  Submission.order(:cached_weighted_average => :desc)
  end

    def featured
    @submissions = Submission.all.order(:cached_votes_score => :desc).limit(5)
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update

      id = params[:id].to_i
    session[:id] = User::ROLES.has_key?(id) ? id : 0
    flash[:success] = "Your new role #{User::ROLES[id]} was set!"
    redirect_to root_path
    respond_to do |format|

      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @submission = Submission.find(params[:id])
    @submission.vote_by :voter => @user
    redirect_to @submission, notice: 'Thanks for voting!'
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:avatar, :title, :applicant, :my_story, :user_id, :first_name, :last_name, :role)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<div class="container submission_form">
<%= simple_form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class:"sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Your Title" %>
  </div>
  <div class="form-group">
    <%= f.label :my_story, class:"sr-only" %>
    <%= f.text_area :my_story, class: "form-control", :rows => 10, placeholder: "Inspire Us!" %>
  </div>
  <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/submissions/_index.html.erb
<div class="container">
<div class="row">
    <% @submissions.each do |submission| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to submission.title, submission %>
          </div>
          <div class="panel-body">
            <%= image_tag submission.user.avatar(:thumb) %><br>
            by <%= submission.user.first_name %><br />
            <span class="posted-at"><%= submission.created_at.strftime('%e %B %Y') %></span><br />
            <p><%= submission.my_story[0..200]%>... <%= link_to "Read More", submission %></p><br>

            <% if current_user.id == submission.user.id %>
              <%= link_to 'Edit', edit_submission_path(submission) %> | 
              <%= link_to 'Back', submissions_path %>
            <% else %>
              <%= link_to vote_submission_path(submission), class: 'vote', method: :put do %>
                <button type="button" class="btn btn-info" aria-label="Left Align">
                  <span class='glyphicon glyphicon-arrow-up'aria-hidden='true'>
                  </span>
                  <span class='badge'><%= submission.get_upvotes.size %></span>
                </button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>
</div>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/featured.html.erb
<div class="container-fluid">
    <div class="c-wrapper">
      <div id="carousel-example-generic" class="carousel slide carousel-fade">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag 'carousel3.png' %>
            <div class="carousel-caption">
              <h2>Get Out of Town.</h2>
            </div>
          </div>
          <div class="item">
            <%= image_tag 'carousel1.png' %>
            <div class="carousel-caption">
              <h2>Build Your Path.</h2>
            </div>
          </div>
          <div class="item">
            <%= image_tag 'carousel2.png' %>
            <div class="carousel-caption">
              <h2>Find Your Place In the World.</h2>
            </div>
          </div>
        </div>

        <!-- Controls -->
        <center>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="icon-next"></span>
        </a>
        </center>
      </div>
    </div>
  </div>

<div class="container-fluid title">
		<h2>Featured Submissions</h2>
		<center><div class="btn-group">
  <button type="button" class="btn btn-danger btn-lg">Scram</button>
  <button type="button" class="btn btn-danger btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
        <li><%= link_to 'All Submissions', submissions_path %></li>
          <li><%= link_to 'Featured', root_url %></li>
<!--           <li><%= link_to 'Donations', donations_path %></li> -->
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Contact', contacts_path %></li>
  </ul>
</div>

  </ul>
</div></center>
</div>

<%= render 'index' %>

<% if can? :create, Submission %>
<%= link_to 'New Submission', new_submission_path %>
<% end %>

app/views/submissions/index.html.erb
<%= render 'shared/navbar' %>

<br>
<main class="all submissions">
  <!-- Uses a transparent header that draws on top of the layout's background -->
<style>
.all_submissions{
  background: url('http://s24.postimg.org/ac55910lh/trailjohnrock1_3.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;
}

.jumbotron{
  vertical-align: center;
  text-align: center;
  margin-top: 60px;
  opacity: 0.90;
  font-family: 'Open Sans Condensed', sans-serif;
  font-weight: 450px; 
  margin-left: 150px;
  margin-right: 150px;

}

</style>

<div class="jumbotron">
  <div align="center">
<h1>All Submissions</h1>


<%= render 'index' %>
​
<% if can? :create, Submission %>
<%= link_to 'New Submission', new_submission_path %>
<% end %>
</div>



</div>
</div>

</main>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/save.home.html.erb
<%= render 'shared/navbar' %>
<div class="container-fluid">
    <div class="c-wrapper">
      <div id="carousel-example-generic" class="carousel slide carousel-fade">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <%= image_tag 'carousel3.png' %>
            <div class="carousel-caption">
              <h2>Get Out of Town.</h2>
            </div>
          </div>
          <div class="item">
            <%= image_tag 'carousel1.png' %>
            <div class="carousel-caption">
              <h2>Build Your Path.</h2>
            </div>
          </div>
          <div class="item">
            <%= image_tag 'carousel2.png' %>
            <div class="carousel-caption">
              <h2>Find Your Place In the World.</h2>
            </div>
          </div>
        </div>

        <!-- Controls -->
        <center>
        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
          <span class="icon-next"></span>
        </a>
        </center>
      </div>
    </div>
  </div>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-primary">
    <div class="panel-heading">
        <%= @submission.title %>
    </div>
    <div class = "panel-body">
        <%= image_tag @submission.user.avatar(:thumb) %><br>
        by <strong><%= @submission.user.id %></strong> <br><span class="posted-at"><%= @submission.created_at.strftime('%e %B %Y') %><br />
        <p><%= @submission.my_story %></p><br />
    </div>
</div>
<div>
    <% if current_user.id == @submission.user.id %>
        <%= link_to 'Edit', edit_submission_path(@submission) %> | 
        <%= link_to 'Back', submissions_path %>
    <% else %>
        <%= link_to vote_submission_path(@submission), class: 'vote', method: :put do %>
        <button type="button" class="btn btn-info" aria-label="Left Align">
            <span class='glyphicon glyphicon-arrow-up'aria-hidden='true'>
            </span>
            <span class='badge'><%= @submission.get_upvotes.size %></span>
        </button>
        <% end %>
    <% end %>
</div>
<br />
<%= form_tag donations_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $10.00</span>
    </label>
    <p>Donate to <%= @submission.user.first_name %> </p>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Donate to your favorite submission"
          data-amount="1000"
          data-locale="auto"></script>
<% end %>
<br>
<div class = "panel panel-success">
    <div class="panel-heading">
        Make a Comment
    </div>
    <div class="panel-body">
        <%= render 'comments/form' %>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-header">
        <h4>Comments</h4>
    </div>
    <% @submission.comments.each do |comment| %>
        <div class="panel-body">
            <p><strong><%= @comment.user_id %></strong> said: </p>
            <p><%= comment.comment_entry %></p>
        </div>
    <% end %>
</div>